
FROM node:24.9-bookworm-slim

RUN apt-get update && \
	apt-get install -y \
		vim \
		git \
		zsh \
		iputils-ping \
		net-tools \
		curl \
		sudo \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY package*.json ./
COPY prisma ./prisma
RUN npm install

COPY . .

CMD ["sleep", "infinity"]